// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * 配置项枚举
 * @readonly
 * @enum {string}
 */
export const ConfigKey = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StorageAccessKey: "StorageAccessKey",
    StorageSecretKey: "StorageSecretKey",
    StorageEndpoint: "StorageEndpoint",
    StorageRegion: "StorageRegion",
    StorageBucket: "StorageBucket",
    AucAppID: "AucAppID",
    AucAccessToken: "AucAccessToken",
    AucClusterID: "AucClusterID",
    LlmBaseURL: "LlmBaseURL",
    LlmModelID: "LlmModelID",
    LlmApiKey: "LlmApiKey",
    RunInBackground: "RunInBackground",
    DesktopNotifications: "DesktopNotifications",
    LogFolding: "LogFolding",
};

/**
 * 响应结构体
 */
export class Response {
    /**
     * Creates a new Response instance.
     * @param {Partial<Response>} [$$source = {}] - The source object to create the Response.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Response}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Response(/** @type {Partial<Response>} */($$parsedSource));
    }
}
