// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ASR配置定义
 */
export class ASRConfig {
    /**
     * Creates a new ASRConfig instance.
     * @param {Partial<ASRConfig>} [$$source = {}] - The source object to create the ASRConfig.
     */
    constructor($$source = {}) {
        if (!("AppID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AppID"] = "";
        }
        if (!("AccessToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AccessToken"] = "";
        }
        if (!("ClusterID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ClusterID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ASRConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ASRConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ASRConfig(/** @type {Partial<ASRConfig>} */($$parsedSource));
    }
}

/**
 * 配置项枚举
 * @readonly
 * @enum {string}
 */
export const ConfigKey = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StorageAccessKey: "StorageAccessKey",
    StorageSecretKey: "StorageSecretKey",
    StorageEndpoint: "StorageEndpoint",
    StorageRegion: "StorageRegion",
    StorageBucket: "StorageBucket",
    AucAppID: "AucAppID",
    AucAccessToken: "AucAccessToken",
    AucClusterID: "AucClusterID",
    LlmBaseURL: "LlmBaseURL",
    LlmModelID: "LlmModelID",
    LlmApiKey: "LlmApiKey",
    RunInBackground: "RunInBackground",
    DesktopNotifications: "DesktopNotifications",
    LogFolding: "LogFolding",
    PromptNote: "PromptNote",
    PromptXiaohongshu: "PromptXiaohongshu",
    PromptWechat: "PromptWechat",
    PromptSummary: "PromptSummary",
};

/**
 * 内容风格枚举
 * @readonly
 * @enum {string}
 */
export const ContentStyle = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    NoteStyle: "note",
    XiaohongshuStyle: "xiaohongshu",
    WeChatStyle: "wechat",
    SummaryStyle: "summary",
};

/**
 * LLM配置定义
 */
export class LLMConfig {
    /**
     * Creates a new LLMConfig instance.
     * @param {Partial<LLMConfig>} [$$source = {}] - The source object to create the LLMConfig.
     */
    constructor($$source = {}) {
        if (!("BaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["BaseURL"] = "";
        }
        if (!("ModelID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ModelID"] = "";
        }
        if (!("ApiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ApiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LLMConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMConfig(/** @type {Partial<LLMConfig>} */($$parsedSource));
    }
}

export class PromptProfile {
    /**
     * Creates a new PromptProfile instance.
     * @param {Partial<PromptProfile>} [$$source = {}] - The source object to create the PromptProfile.
     */
    constructor($$source = {}) {
        if (!("style" in $$source)) {
            /**
             * @member
             * @type {ContentStyle}
             */
            this["style"] = ContentStyle.$zero;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {ConfigKey}
             */
            this["key"] = ConfigKey.$zero;
        }
        if (!("default_prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default_prompt"] = "";
        }
        if (!("custom_prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["custom_prompt"] = "";
        }
        if (!("effective_prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["effective_prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromptProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptProfile(/** @type {Partial<PromptProfile>} */($$parsedSource));
    }
}

/**
 * 响应结构体
 */
export class Response {
    /**
     * Creates a new Response instance.
     * @param {Partial<Response>} [$$source = {}] - The source object to create the Response.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Response}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Response(/** @type {Partial<Response>} */($$parsedSource));
    }
}

/**
 * TOS配置定义
 */
export class TOSConfig {
    /**
     * Creates a new TOSConfig instance.
     * @param {Partial<TOSConfig>} [$$source = {}] - The source object to create the TOSConfig.
     */
    constructor($$source = {}) {
        if (!("AccessKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AccessKey"] = "";
        }
        if (!("SecretKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SecretKey"] = "";
        }
        if (!("Endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Endpoint"] = "";
        }
        if (!("Region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Region"] = "";
        }
        if (!("Bucket" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Bucket"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TOSConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TOSConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TOSConfig(/** @type {Partial<TOSConfig>} */($$parsedSource));
    }
}
