// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @param {number} taskID
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function ClearChatHistory(taskID) {
    return $Call.ByID(1921588798, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} taskID
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function GetChatHistory(taskID) {
    return $Call.ByID(229623017, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function GetQuickPrompts() {
    return $Call.ByID(788006463).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SendChatMessage 接收用户消息，立即保存后在后台启动流式响应。
 * 实际 AI 回复通过 Wails 事件推送：
 *   - "chat_token": {"task_id": int, "token": string}
 *   - "chat_done":  {"task_id": int}
 *   - "chat_error": {"task_id": int, "error": string}
 * @param {number} taskID
 * @param {string} userMessage
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function SendChatMessage(taskID, userMessage) {
    return $Call.ByID(970788278, taskID, userMessage).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.Response.createFrom;
