// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @param {string} key
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function ConfigExists(key) {
    return $Call.ByID(1452669869, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function DeleteConfig(key) {
    return $Call.ByID(3228890338, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function GetAllConfigs() {
    return $Call.ByID(2286784159).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function GetConfig(key) {
    return $Call.ByID(3089215939, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function SaveConfig(key, value) {
    return $Call.ByID(4973740, key, value).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.Response.createFrom;
