// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @param {models$0.ContentStyle} style
 * @returns {$CancellablePromise<models$0.PromptProfile>}
 */
export function BuildPromptProfile(style) {
    return $Call.ByID(984555132, style).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * 确保配置项有默认值
 * @param {models$0.ConfigKey} key
 * @param {string} defaultValue
 * @returns {$CancellablePromise<void>}
 */
export function EnsureConfigDefaultValue(key, defaultValue) {
    return $Call.ByID(3753997769, key, defaultValue);
}

/**
 * Legacy compatibility methods that return models.Response
 * @param {models$0.ConfigKey} key
 * @param {string} defaultValue
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function EnsureConfigDefaultValueResp(key, defaultValue) {
    return $Call.ByID(4075184007, key, defaultValue).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * 获取ASR配置
 * @returns {$CancellablePromise<models$0.ASRConfig | null>}
 */
export function GetASRConfig() {
    return $Call.ByID(4007572771).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * 获取布尔类型的配置项值，如果未设置或解析失败则返回默认值
 * @param {models$0.ConfigKey} key
 * @param {boolean} defaultValue
 * @returns {$CancellablePromise<boolean>}
 */
export function GetBoolConfig(key, defaultValue) {
    return $Call.ByID(399331395, key, defaultValue);
}

/**
 * @param {models$0.ConfigKey} key
 * @param {boolean} defaultValue
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function GetBoolConfigResp(key, defaultValue) {
    return $Call.ByID(1470501433, key, defaultValue).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {models$0.ConfigKey} key
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function GetConfig(key) {
    return $Call.ByID(3089215939, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {models$0.ContentStyle} style
 * @returns {$CancellablePromise<string>}
 */
export function GetCustomPrompt(style) {
    return $Call.ByID(199455176, style);
}

/**
 * 获取是否开启桌面通知的配置
 * @returns {$CancellablePromise<boolean>}
 */
export function GetDesktopNotificationsConfig() {
    return $Call.ByID(4128627187);
}

/**
 * @param {models$0.ContentStyle} style
 * @returns {$CancellablePromise<string>}
 */
export function GetEffectivePrompt(style) {
    return $Call.ByID(2686113764, style);
}

/**
 * 获取LLM配置
 * @returns {$CancellablePromise<models$0.LLMConfig | null>}
 */
export function GetLLMConfig() {
    return $Call.ByID(346161410).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function GetPromptProfiles() {
    return $Call.ByID(2804435273).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * 获取TOS配置
 * @returns {$CancellablePromise<models$0.TOSConfig | null>}
 */
export function GetTOSConfig() {
    return $Call.ByID(3815533851).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Frontend compatibility methods
 * @param {models$0.ConfigKey} key
 * @param {string} value
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function SaveConfig(key, value) {
    return $Call.ByID(4973740, key, value).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.PromptProfile.createFrom;
const $$createType1 = models$0.Response.createFrom;
const $$createType2 = models$0.ASRConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.LLMConfig.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = models$0.TOSConfig.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
