// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * DownloadMarkdown downloads the markdown content for a specific task
 * @param {number} taskID
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function DownloadMarkdown(taskID) {
    return $Call.ByID(1497659073, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DownloadSubtitles downloads the subtitle content for a specific task in the specified format
 * @param {number} taskID
 * @param {string} format
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function DownloadSubtitles(taskID, format) {
    return $Call.ByID(620866277, taskID, format).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<number>}
 */
export function GetFileSize(filePath) {
    return $Call.ByID(2216568243, filePath);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function GetTaskByID(id) {
    return $Call.ByID(3731936101, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function GetTaskList() {
    return $Call.ByID(1890625269).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} filePath
 * @param {string} contentStyle
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function NewTask(filePath, contentStyle) {
    return $Call.ByID(1542729443, filePath, contentStyle).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function ResetStuckTasks() {
    return $Call.ByID(1021869045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.Response.createFrom;
