// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function GetTaskList() {
    return $Call.ByID(1890625269).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} filePath
 * @param {string} contentStyle
 * @returns {$CancellablePromise<models$0.Response>}
 */
export function NewTask(filePath, contentStyle) {
    return $Call.ByID(1542729443, filePath, contentStyle).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.Response.createFrom;
